version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
  jms:
    image: rmohr/activemq
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: ingjulianvega/mssc-asu-eureka
    ports:
      - 8761:8761
  #config:
  #  image: sfgbeerworks/sfg-brewery-config
  #  ports:
  #    - 8888:8888
  #  depends_on:
  #    - eureka
  #  environment:
  #    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
  #    EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  administration-method:
    image: ingjulianvega/mssc-asu-administration-method
    ports:
      - 8094:8094
    depends_on:
      - eureka
#      - config
#      - jms
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  arl:
    image: ingjulianvega/mssc-asu-arl
    ports:
      - 8084:8084
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  gender:
    image: ingjulianvega/mssc-asu-gender
    ports:
      - 8081:8081
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    #      SPRING_ARTEMIS_HOST: jms
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  occupation:
    image: ingjulianvega/mssc-asu-occupation
    ports:
      - 8082:8082
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  eps:
    image: ingjulianvega/mssc-asu-eps
    ports:
      - 8083:8083
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  document-type:
    image: ingjulianvega/mssc-asu-document-type
    ports:
      - 8085:8085
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    #      SPRING_ARTEMIS_HOST: jms
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  disease:
    image: ingjulianvega/mssc-asu-disease
    ports:
      - 8087:8087
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  evidence-type:
    image: ingjulianvega/mssc-asu-evidence-type
    ports:
      - 8100:8100
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  evidence:
    image: ingjulianvega/mssc-asu-evidence
    ports:
      - 8088:8088
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  patient:
    image: ingjulianvega/mssc-asu-patient
    ports:
      - 8107:8107
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  companion:
    image: ingjulianvega/mssc-asu-companion
    ports:
      - 8106:8106
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  body-part:
    image: ingjulianvega/mssc-asu-body-part
    ports:
      - 8092:8092
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  disability-type:
    image: ingjulianvega/mssc-asu-disability-type
    ports:
      - 8098:8098
    depends_on:
      - eureka
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  gateway:
    image: ingjulianvega/mssc-asu-gateway:latest
    ports:
      - 8112:8112
    depends_on:
      - eureka
#      - config
      - administration-method
##      - beer-service
##      - order-service
##      - inventory-failover
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"