version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
  jms:
    image: rmohr/activemq
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: ingjulianvega/mssc-asu-eureka
    ports:
      - 8761:8761
  #config:
  #  image: sfgbeerworks/sfg-brewery-config
  #  ports:
  #    - 8888:8888
  #  depends_on:
  #    - eureka
  #  environment:
  #    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
  #    EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  administration-method:
    image: ingjulianvega/mssc-asu-administration-method
    ports:
      - 8094:8094
    depends_on:
      - eureka
#      - config
#      - inventory
#      - jms
#    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
#      SPRING_ZIPKIN_BASEURL: http://zipkin
##      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#      SPRING_ARTEMIS_HOST: jms
#    labels:
#      collect_logs_with_filebeat: "true"
#      decode_log_event_to_json_object: "true"
  gateway:
    image: ingjulianvega/mssc-asu-gateway:latest
    ports:
      - 8112:8112
    depends_on:
      - eureka
#      - config
      - administration-method
##      - beer-service
##      - order-service
##      - inventory-failover
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://gateway:8761/eureka/
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"